apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: harmonia-api
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/request-timeout: "120"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/vpc-access-connector: harmonia-vpc-connector
        run.googleapis.com/cloudsql-instances: ""
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 20
      timeoutSeconds: 120
      serviceAccountName: ""
      containers:
        - image: ""
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 30
          env:
            - name: ENVIRONMENT
              value: production
            - name: LOG_LEVEL
              value: INFO
